### PR TITLE
Allow custom authentication functions

### PR DESCRIPTION
**Pull request by emarj**
Hi again,

For a project of mine I needed to extend the package in order to have multiple users and to check credentials against a database to do some quick prototyping.

I managed to find a way to easily extend the current package, without completely changing it, providing an high level of customisability. I'd like to share the edits with you in the case you may be interested in merging it.
The code still needs some more comments, maybe some renaming and the README should updated.

I will be happy to hear thoughts, suggestions, etc.

Cheers,

Marco

___
_Below a brief description of the upgrade:_

I think the code almost speaks by itself (I also updated the examples). I added a custom function type `AuthFunc` that is used to authenticate the user. This function returns also a slice of bytes that identify the user (could be "user:pass" or another identifier) which is used, as before, as a password to generate the hash. The original behaviour of the package is obtained by using a really simple `AuthFunc` (see `NewSimpleAuthFunc`)

### CODE REVIEW

**Comment by jpillora** [comment]
Hey @emarj nice feature, but I think the exposed API could be simpler.

Currently `SetUserPass` replaces the single user (`auth []byte`). Instead of using `auth []byte` we could use a `users map[string]string`, then `SetUserPass` would reset the map back to a single user (this probably needs documentation).

Then, we only need to add two new methods `AddUser(user, pass string)` and `RemoveUser(user string)`, both of which simply update the map.

Note, caching and creating scrypt blob will still need to concat the user (key) and password (value).

No worries if it's too much work 👍

**Comment by emarj** [comment]
You mean by removing the `AuthFunc` mechanism? Well, in that way we lose the customisability. For example one could authenticate the users using a database by writing a custom `AuthFunc` that performs the query (see `examples/database` on the last commit).

**Comment by jpillora** [comment]
Ah yes that's true, though would caching still kick in could be out of sync
with the DB?

**Comment by jpillora** [comment]
Whats your database use-case? If you have a database, you could create and store session IDs, which is more secure than keeping `scrypt(username:password)` in a cookie

**Comment by emarj** [comment]
> If you have a database, you could create and store session IDs, which is more secure than keeping `scrypt(username:password)` in a cookie

Yeah, definitely. The `AuthFunc` is returning the an `auth` string that can be different from the `user:password` (see examples), but the problem arise when we have to access by cookie. We should also add a `CookieAuthFunc` to make everything work with custom access methods.

I tried to play a bit with it, and I ended up creating and interface

```
type Authenticator interface {
	WithCreds(user, pass string) (bool, []byte, error)
	WithCookie(b64 string) error
}
```
and by adding an `Authenticator` type field to `CookieAuth`. If I'll have time I will commit this to show what I mean.


> Whats your database use-case?

Nothing fancy, I wanted to quickly implement a multiuser basic auth for prototyping without writing down a proper login system with login form and stuff.

I think that for testing, HTTP Basic Auth + HTTPS can be quite handy and not *that* insecure.

**Comment by emarj** [comment]
I sketched the idea I was talking about. The caching is not yet fully implemented but in this case hashing cache should live in the `Authenticator`, that "knows what he wants", and in `CookieAuth` only the Base64 Encoding cache should be present...
I mean, in the end `CookieAuth` should be agnostic to the "authentication logic" and just provide the way of expressing it through Basic Auth and Cookie.

I feel like something good on these lines could be done, but I think I have yet to find the proper way.

PS I deleted the custom examples for now

**Pull request closed without merging**
